services:
  caddy:
    image: caddy:2-alpine
    container_name: marwa-caddy-fpm
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ../:/var/www/html
      - ./caddy/Caddyfile.fpm:/etc/caddy/Caddyfile:ro
      # - ./caddy/data:/data
      # - ./caddy/config:/config
    working_dir: /var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: marwa-php-fpm
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
    expose:
      - "9000"
